### ISSUE TITLE
Make JedisPubSub Observable?

### ISSUE THREAD

**Issue by yaxing** [redis/jedis#1220]
https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/JedisPubSub.java

Have we considered making JedisPubSub an Observable?

``` java
public abstract class JedisPubSub extends Observable {
 ...
}
```

This way it'd be more flexible to react on messages by adding Observer instances to JedisPubSub instance and do:

``` java
public void onMessage(String channel, String message) {
        this.setChanged();
        this.notifyObservers(parsedMessage);
}
```

**Comment by sazzad16** [comment]
Observer and Observable are deprecated in Java 9.

References:
1. Oracle JavaDoc: [Observable (Java SE 11 & JDK 11 )](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Observable.html)
2. Stackoverflow: [Observer is deprecated in Java 9. What should we use instead of it?](https://stackoverflow.com/questions/46380073/observer-is-deprecated-in-java-9-what-should-we-use-instead-of-it)
