### ISSUE TITLE
Jedis should provide pre-release binaries/snapshots

### ISSUE THREAD

**Issue by mp911de** [redis/jedis#1369]
Jedis is a widely used client for Redis. Each release comes with a number of changes that are only available with own/custom snapshots build or by awaiting the final release.

It's not possible for users to run tests against development/pre-release binaries because these are not available. 

Please provide at least snapshot builds (in [Sonatype's OSS Snapshot repo](https://oss.sonatype.org/content/repositories/snapshots/)), better, release candidates as part of the release process. Users can include pre-release binaries in own builds and verify for breaking changes.

Publishing snapshots with TravisCI is feasible; I can support you if you want. Publishing pre-releases requires changes in the release process and is more a process issue than a technical.

**Comment by HeartSaVioR** [comment]
Since I'm involved in Apache project, I like release candidate in release process.
One thing I'm wondering is that does Jedis really have early adopters or steady contributors who can check for new release candidate more thoughtfully than our unit tests. 

Back to the recent issue and talking about that a bit, in my perspective this issue was occurred because we modified unit tests which checks return type. That pull request even skipped pair review.

If we can automate SDR tests to every snapshot builds of Jedis or RC of Jedis, it might make sense. Other than that, we need to answer ourselves that who would test for us.

**Comment by mp911de** [comment]
Providing snapshots/release candidates creates options although it may lack a broad adoption. You can tell users to switch to a SNAPSHOT to test a particular case (without the need to rebuild the driver yourself). Release cycles with snapshot/release candidate(s)/GA release are beneficial for short feedback cycles and discovering issues early, yet it does not cure all pains (because people are on vacation, not motivated in updating, …). You provide a possibility to test your library. No RC/Snapshots means a higher barrier to give a new version a try.

I don't think it's just an issue to Spring Data Redis only. We run builds in several projects against [different driver versions](https://travis-ci.org/spring-projects/spring-data-mongodb/builds/152996400), some of them are `SNAPSHOT`s to eagerly discover issues.

[Here's](https://gist.github.com/letmaik/4060735) a link that contains a guide how to install deployment to Sonatype's. The only missing bit is filtering for `SNAPSHOT` in the `pom.xml`.

**Comment by HeartSaVioR** [comment]
@mp911de 
I'm OK to build SNAPSHOT (nightly, or every commit by Travis CI) for all active version lines.
This should be automated and we don't need to take much time to care.

I'd be much appreciated if you provide a patch for that since I don't want to spent time to dig (explore?).

Having RCs in release process is different as you said. It can't be automated since it's more alike process, so it requires more time (linearly to the attempt of RCs) for release manager, and technically only @xetorthio is a release manager. (I think it would be better to correct this.)

We have three active collaborators including owner who all have our daily jobs and AFAIK we all don't use Redis for our daily jobs (even @xetorthio and @marcosnils are not using Java) so we need to minimize (opposite to expand) the processes regarding Jedis. 

I had been spending more time to Jedis before I was involved to Apache Storm. Before that I could handle more things like this case, and I can't do that now even though contributing Apache Storm is my daily job now. It requires my whole concentration for that.

@xetorthio @marcosnils What do you think?

**Comment by marcosnils** [comment]
@mp911de @HeartSaVioR 

I do also believe that it should be amazing to have nightly builds or RC's. We need the invervention of @xetorthio as he's the only one allowed to publish to Sonatype.

**Comment by gkorland** [comment]
@marcosnils is there any progress with that?

**Comment by marcosnils** [comment]
Not for the moment.

**Comment by gkorland** [comment]
@marcosnils I can take it

**Comment by gkorland** [comment]
Until we'll have an official one I published a milestone artifact with the latest on the maven main repository 
https://mvnrepository.com/artifact/com.redislabs/jedis

**Comment by gkorland** [comment]
@marcosnils thanks to @xetorthio I can now have access to the sonatype account and can release new artifacts.
Two immediate steps I think we should take:
1. Release SNAPSHOTS from the master 
2. Release 3.0.0-M1 as a first milestone release for the 3.0.0

**Comment by sazzad16** [comment]
It has been sometime that the snapshots are being published.

E.g. at this moment

```
  <repositories>
    <repository>
      <id>snapshots-repo</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
  </repositories>
```
and
```
  <dependencies>
    <dependency>
      <groupId>redis.clients</groupId>
      <artifactId>jedis</artifactId>
      <version>3.5.0-SNAPSHOT</version>
    </dependency>
  </dependencies>
```
