### ISSUE TITLE
get current master is not working in one scenario with redis-sentinel configuration

### ISSUE THREAD

**Issue by rajatgoyal247341** [redis/jedis#2193]
### Expected behavior
      Jedis library should get new master after failover
### Actual behavior
      Library is never able to get current master.

### Steps to reproduce:
My current conf is like : 
There are 3 redis-process: M1,R1,R2
There are 3 sentinels : S1, S2, S3 ( all are monitoring M1)

I have configured my java application using RedisSentinelConfiguration as S1, S2 then S3 in order. 
PS : My application is a spring-boot application.
1)  Application comes up and tries to make connection with Sentinels and get current master. 
2)  Now lets say S1 goes down. At this time I get exceptions in logs about connection timeout to S1, while redis requests are served with M1 as usual.
3) Now let's say M1 goes down. As a failover process new master is elected, R1 is promoted as new  master, which I confirmed by sentinel command. While at this point, I keep on getting same connection timeout error to S1, **but now jedis never able to find new master**. So no redis requests are served at this time. Ideally as per documentation at https://redis.io/topics/sentinel-clients, it should try to ask the new master with S2 ( next one in list), but it is not doing.

### Redis / Jedis Configuration
Explained above
#### Jedis version:
3.3.0
#### Redis server version:
4.0.9
#### spring-data-redis version:
2.2.3.RELEASE
#### Java version:
JAVA-11

**Comment by rajatgoyal247341** [comment]
can someone please help to check this.

**Comment by MichaHoffmann** [comment]
We also hit that issue in production.

After some debugging, it seems that the masterAddress is updated via the "+switch-master" subscription in the `MasterListener` of `JedisSentinelPool`, or on some connection loss. [To quote the sentinel integration documentation](https://redis.io/topics/sentinel-clients): `However update messages received via Pub/Sub should not substitute the above procedure, since there is no guarantee that a client is able to receive all the update messages.`

Maybe the master update got lost because it was not received via the pub/sub mechanism?
