### ISSUE TITLE
Feature Request: The Exception message should show Min, Max, MinIdle, MaxIdle and other useful parameters in the exception

### ISSUE THREAD

**Issue by arashnikoo** [redis/jedis#2541]
It would be really nice to include some additional information for the following exception:
`redis.clients.jedis.exceptions.JedisExhaustedPoolException: Could not get a resource since the pool is exhausted`

I suggest to show the following parameters in the exception message:
Min=x, Max=x, MinIdle=x, MaxIdle=x, Current=x

**Comment by sazzad16** [comment]
That exception is based on exception occurred in `GenericObjectPool.borrowObject()` method of commons-pool2. If Jedis tries to provide those information, it can't do it fairly because the state that generated the issue (in commons-pool2) is unlikely to be true when it reaches Jedis.

If you think it's necessary, please raise a ticket in [Commons Pool issue tracker](https://issues.apache.org/jira/browse/POOL). Thanks!

**Comment by arashnikoo** [comment]
That makes sense. I open a ticket with that project:
https://issues.apache.org/jira/browse/POOL-395

**Comment by arashnikoo** [comment]
The issue has been updated and will be fixed in 2.11.0.
https://issues.apache.org/jira/browse/POOL-395

There will be an option to enable statistics via BaseGenericObjectPool:

`BaseGenericObjectPool#setMessagesStatistics(true).`
