### ISSUE TITLE
Jedis and Redis Compatibility matrix

### ISSUE THREAD

**Issue by salaboy** [redis/jedis#2940]
### Expected behavior

Having a compatibility matrix in the main README.md file of this repo. 

I am having a hard time figuring out how compatible are different versions of Jedis with different versions of Redis. 
is there any place already documenting this? 
I am curious about Redis 6.x specifically.

**Comment by sazzad16** [comment]
Any Jedis version in recent few years are compatible with:

- Any Redis version after that. It may miss some commands/arguments.
- Any Redis version before that without huge time gap. It may have some commands/arguments that are absent in Redis which should not be issue if those methods do not get called.

@salaboy What exact problems are you facing?

**Comment by sazzad16** [comment]
Dupe #2267

**Comment by salaboy** [comment]
I think the problem is that I couldn't get that answer in the main readme .. maybe I missed something..

**Comment by crazyjat** [comment]
@sazzad16 
As someone new to redis, this also annoys me. Redis is at version 7 and Jedis is on 4.3.1. Since the version numbers don't line up, how exactly do you propose we determine which is newer, older, etc. The point is it is a PITA to have to track down the compatible versions and if I had my way, I simply wouldn't use your tool or redis for this simple reason alone. But I have no choice. So it would be great if you guys could make my job just a little easier and break down what versions are compatible with what.
