### ISSUE TITLE
Jedis.get returning TRUE 

### ISSUE THREAD

**Issue by BalajiGuruanywhere** [redis/jedis#2945]
sometimes while fetching the data, jedis.get("key") returns TRUE instead of the original object

**Comment by sazzad16** [comment]
@BalajiGuruanywhere This information is really not enough. Please provide detailed information.

However,
1. Which Jedis version are you using?
2. What do you see using other clients, e.g. `redis-cli`?

**Comment by BalajiGuruanywhere** [comment]
We are using jedis 3.7.0, we thought async might be the problem, but jedis doesn't support async yet, but it's not happening everytime, it's only happening sometime

**Comment by sazzad16** [comment]
@BalajiGuruanywhere Are you using `Jedis` object without `JedisPool` in a multi-threaded environment?

**Comment by BalajiGuruanywhere** [comment]
Yes We are, using JedisPool only we are getting the resource and then doing the operations, JedisPool.getResource();

**Comment by BalajiGuruanywhere** [comment]
any update?

**Comment by sazzad16** [comment]
> **we are deserializing bytes that are fetched from cache using jedis.get()**, but while deserializing we are getting exception saying that the byte for "TRUE" cannot be deserialized

This is not a Jedis issue. Check your deserializer and/or actual data.

Jedis.get() doesn't return TRUE on its own. It can return TRUE if and only if the actual data is TRUE. There's nothing in your comments that state otherwise.
So, either your actual data is TRUE or your deserializer has issues. We can't help in either scenario.

Thank you.
