### ISSUE TITLE
Does jedis support valkey connections ?

### ISSUE THREAD

**Issue by DipalPrajapati** [redis/jedis#3916]
Does jedis supports interface to Valkey in java?

**Comment by mortensi** [comment]
Jedis is a Redis official client library. As a RESP-compatible library, it can work with forks without guaranteeing future compatibility due to API changes or deprecations. In particular, Jedis supports hash-field expiration and other Redis-only advanced features like indexed searches, the JSON data type, time series, and probabilistic data structures that other Redis clones do not offer.
