### ISSUE TITLE
Proper naming to interfaces

### ISSUE THREAD

**Issue by HeartSaVioR** [redis/jedis#824]
From #607, I've changed interfaces name but reverted for initiating discussion about it.

MultiKeyBinaryRedisPipeline -> MultiKeyBinaryCommandsPipeline

There're lots of inconsistent interface names because of not having prefix / postfix rules or conventions.

I've mentioned earlier about it by https://groups.google.com/d/msg/jedis_redis/r1axS6Lckfg/npldlkX2-i4J .
But it didn't get any opinions, and @marcosnils agrees that we can change improper interface names, so I've posted to github issue again.

So please refer Google Groups link and show your opinions.
Thanks!

**Comment by nykolaslima** [comment]
As a really new contributor, I think it would be nice to refactor the packages. If the project was structured in a more "logic" way, it would be easier to understand.

Having proper packages that represent not only the major domains(`redis.clients.jedis`, `redis.clients.jedis.exception`, `redis.clients.jedis.util`) but also the subdomains(`connection`, `data structure`, etc.) makes the understanding easier and it can also help us to define boundaries. For instance, the `class X` in the `connection` package can only be used by this package. This helps us because when we change something, we know what's the affected domain.

**Comment by HeartSaVioR** [comment]
@nykolaslima 
I already talked re-structure, about 1 years ago.  
https://groups.google.com/d/msg/jedis_redis/r1axS6Lckfg/Ylur-RRXiQoJ
Seems like preparing major release is a chance to go on? :)

**Comment by nykolaslima** [comment]
Yes! Let's do it for the next 3.0.

**Comment by HeartSaVioR** [comment]
@nykolaslima 
We're going to move interfaces to new packages - #1085 . 
Hope that will be a good starting point of repackaging.
Your idea would be greatly appreciated!

@xetorthio @marcosnils @nykolaslima 
Next movement is renaming interfaces. I think it's time to discuss naming convention for interfaces.
